### ISSUE TITLE
Add a timeline page to cover tomesh history

### ISSUE THREAD

**Issue by dcwalk** [tomeshnet/tomesh.net#66]
We've created some [draft copy](https://pad.riseup.net/p/szcVQvcpfixX) for a **timeline page** here and discussed adding it to showcase the projects we are working on. 

---

- Current working title (in main navigation): Timeline
- Create timeline Collection
- Timeline content: Small (Tweet-size), Medium (400 words?), Large (long-form)
  - Setup Front-matter to represent different sized content
  - Stick to chronological sorting for now
- Create top-level page in repository
- Reference for CSS/JS: https://webdesign.tutsplus.com/tutorials/building-a-vertical-timeline-with-css-and-a-touch-of-javascript--cms-26528
- Account for image and text content

---

- [x] Add _Timeline_ to top navigation
- [x] Create Timeline page
- [x] Create collection for Timeline events
- [x] Create Timeline event post template (front matter, format)
- [x] Display Timeline posts on page
- [x] CSS/JS

**Comment by garrying** [comment]
@slowmanchan We had a look at the timeline so far and there are a few things that we should consider for our next review:
- [x] Add in content from https://pad.riseup.net/p/szcVQvcpfixX to see how the content we have looks so far
- [x] Revise the blue and black colour combo. Maybe do away with the blue so that text is more legible?
- [x] Account for a title heading for a block (e.g. date, title, body, etc.)
- [x] Reverse the order (most recent should be at the top)
- [x] General style refinements. Kickstarter is a good reference, [an example](https://www.kickstarter.com/projects/uniondocs/living-los-sures/updates)

**Comment by dcwalk** [comment]
Hey, looking good! I'm a little out of the code so leaving that to you two, the copy needs some refining I'm noticing. Also, what about images?

**Comment by dcwalk** [comment]
Maybe this is silly, but could we have things like the ["Project Launched"](https://www.kickstarter.com/projects/uniondocs/living-los-sures/updates) in the kickstarter... a rectangle that breaks apart the line to draw focus on a key moment)

I'm imagining one for When we like officially call ourselves toronto mesh ( 🎆 :champagne:  )

**Comment by benhylau** [comment]
May be easier to sit together during next virtual meet to finalize copy?

**Comment by dcwalk** [comment]
I did a pass, formatted, made tense consistent, etc...  I think it looks 👌  for a first iteration where it is at, but would be nice to run through it at the check in like you say @benhylau

**Comment by garrying** [comment]
Looking at this on mobile and the menu is getting compressed. 1096d75 is a patch until we have a better design solution.
